### ISSUE TITLE
Google reCaptcha makes the site unreachable from Tor at will

### ISSUE THREAD

**Issue by leafcutterant** [ethgasstation/ethgasstation#6]
This happens sometimes and it's regardless of the exit node/circuit you use.

**Comment by ghost** [comment]
This isn't a problem with this code, but rather with the *ethgasstation.info* site. Because of this, I am closing this issue.

We are using CloudFlare to handle some of the load on EGS right now which is likely why Tor exits are being ReCAPTCHA'd. If there's enough interest, I could set up an API frontend to run on a hidden service, but probably won't support the whole UI via Tor.

**Comment by leafcutterant** [comment]
Well, what better option does one have to report such an issue?

Couldflare is making anonymous access harder and harder. I do believe this is a hindrance experienced by many. Count me in as interest. Even just the very basic info on a hidden service would be helpful.
